### ISSUE TITLE
Fix button selection size

### ISSUE THREAD

**Issue by fneedly** [gschick3/recinv#9]
The yellow is where it currently allows selection. The red is where we would like it to.

![login-page](https://github.com/gschick3/recinv/assets/18488647/85872fb1-b5e5-478b-bf36-955ff24a539f)

**Comment by josmoo** [comment]
This issue is actually more complicated than (at least what I) initially thought. 

If you have either no username or no password, clicking on the button but not the text will correctly not redirect you to the homepage. If you do have both, then it won't redirect you still, but you won't have the error message pop up. This could be intentional and you're waiting to see if you can check against the database that the info is valid? @Hailey1005 

Side effect that is definitely a bug though, clicking on the text of the button will always redirect you to the homepage regardless of what is in username or password.

**Comment by fneedly** [comment]
@josmoo it doesn't redirect because it doesn't work lol. If you hover over the button and not the text, it shows no url. The link is only on the text.

**Comment by Hailey1005** [comment]
@gschick3 oh yeah I've set the 'Sign In' text as a link to the Homepage for today's demo purposes. I can adjust it to cover the entire button if needed!
@josmoo   there is nothing connected to the database at the moment so yeah you can put whatever in the username and password and it still takes you to the homepage

**Comment by fneedly** [comment]
This was fixed at some point, but we missed this.

**Comment by Hailey1005** [comment]
@gschick3 we didn't miss it. I fixed and closed it then someone REOPENED it
